# Configure app
DEBUG = True
APP_NAME = 'PyDino'
SECRET_KEY = 'REPLACE THIS WITH SOMETHING SUPER SECRET FOR PRODUCTION'
DOMAIN = 'REPLACE WITH DOMAIN'

# DB Configurations
POSTGRES_USER = 'REPLACE WITH USER'
POSTGRES_PW = 'REPLACE WITH PASSWORD'
POSTGRES_URL = 'REPLACE WITH DOMAIN'
POSTGRES_PORT = '5432'
POSTGRES_DB = 'REPLACE WITH DB'
DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}:{port}/{db}'.format(
    user=POSTGRES_USER, pw=POSTGRES_PW, url=POSTGRES_URL,
    port=POSTGRES_PORT, db=POSTGRES_DB)
SQLALCHEMY_DATABASE_URI = DB_URL
SQLALCHEMY_TRACK_MODIFICATIONS = False
JSON_SORT_KEYS = False

# JWT Cookie Configurations
JWT_TOKEN_LOCATION = ['cookies']
JWT_COOKIE_SECURE = False  # Set to True in production
JWT_ACCESS_COOKIE_PATH = '/api/'
JWT_ACCESS_CSRF_COOKIE_PATH = '/api/'
JWT_REFRESH_COOKIE_PATH = '/token/refresh'
JWT_REFRESH_CSRF_COOKIE_PATH = '/token/refresh'
JWT_COOKIE_SAMESITE = 'Strict'
# JWT_COOKIE_DOMAIN = 'localhost'
JWT_COOKIE_CSRF_PROTECT = True
JWT_SECRET_KEY = 'REPLACE THIS WITH SOMETHING SUPER SECRET FOR PRODUCTION'

# Flask-Mail settings
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USE_TLS = False
MAIL_USERNAME = 'REPLACE WITH EMAIL'
MAIL_PASSWORD = 'REPLACE WITH PASSWORD'
MAIL_DEFAULT_SENDER = '<PyDino support@pydino.com>'
